#! /bin/sh
#
# FlyingBBQ @ Bar
#

## Colors

. ~/.config/lemonbar/bar_colors

## Config
screen_width=1920
bar_fifo=/tmp/bar-fifo
bar_font="-f -misc-tamsyn-medium-r-normal--16-116-100-100-c-80-iso8859-1"
bar_width=1500
bar_height=30
bar_y=10
bar_x=$(( ($screen_width - $bar_width)/2 ))

geometry="-g ${bar_width}x${bar_height}+${bar_x}+${bar_y}"
parameters=" $bar_font -B $a$bg -F $a$fg -u 3"

# make fifo file
[ -e "$bar_fifo" ] && rm "$bar_fifo"
mkfifo "$bar_fifo"

# padding
herbstclient pad 0 $(( $bar_height+$bar_y ))

## Modules
# date
while :
do
    echo 'D'$(date "+%a %b %d");
    sleep 1;
done > $bar_fifo &

# time
while :
do
    echo 'H'$(date "+%T");
    sleep 1;
done > $bar_fifo &

# memory
while :
do
    echo 'M'$(free -m | grep Mem | awk '{printf "%2.f", $3/$2 * 100.0}');
    sleep 1;
done > $bar_fifo &

# cpu
while :
do
    echo -e 'C'$(awk -v a="$(awk '/cpu /{print $2+$4,$2+$4+$5}' /proc/stat; sleep 0.5)" '/cpu /{split(a,b," "); printf "%2.f", 100*($2+$4-b[1])/($2+$4+$5-b[2]) }'  /proc/stat)
    sleep 1;
done > $bar_fifo &

# temp
while :
do
    echo 'T'$(cat /sys/class/thermal/thermal_zone0/temp | awk '{print $1/1000}')
    sleep 3;
done > $bar_fifo &

# email
while :
do
    echo 'E'$(python ~/code/scripts/.mail)
    sleep 10;
done > $bar_fifo &

# window info
while :
do
    echo 'I'$(herbstclient attr clients.focus.title)
    sleep .5;
done > $bar_fifo &

# tags
herbstclient -i | grep --line-buffered "tag_change" > $bar_fifo &

## bar
~/.config/lemonbar/bar_fifo < "$bar_fifo" | lemonbar $geometry$parameters | sh &

wait
