#! /bin/sh

. ~/.config/lemonbar/bar_colors

while read -r line ; do
    case $line in
        S*)
            songtime="$highlight ${line#?}$clr"
            ;;
        A*)
            artist="$normal ${line#?}$clr"
            ;;
        V*)
            volume="$normal VOL $highlight${line#?}%$clr"
            ;;
        W*)
            wm_infos="$dark-<$clr${line#?}$dark >-$clr"
            ;;
    esac
    printf "%s\n" "%{l}$songtime $artist%{c}$wm_infos%{r}$volume"
done
