#! /bin/sh
#
# FlyingBBQ @ Bar Left
#

## Colors

. ~/.config/lemonbar/bar_colors

## Config
screen_width=1920
bar_fifo=/tmp/bar-fifo-l
bar_font="-f -misc-tamsyn-medium-r-normal--16-116-100-100-c-80-iso8859-1"
bar_width=1200
bar_height=30
bar_y=10
bar_x=$(( ($screen_width - $bar_width)/2 ))

geometry="-g ${bar_width}x${bar_height}+${bar_x}+${bar_y}"
parameters=" $bar_font -B $a$bg -F $a$fg -u 3"

# make fifo file
[ -e "$bar_fifo" ] && rm "$bar_fifo"
mkfifo "$bar_fifo"

# padding
herbstclient pad 0 $(( $bar_height+$bar_y ))

## Modules
# date
while :
do
    echo 'D'$(date "+%a %b %d");
    sleep 60;
done > $bar_fifo &

# time
while :
do
    echo 'H'$(date "+%T");
    sleep 1;
done > $bar_fifo &

# memory
while :
do
    perc=$(free -m | grep Mem | awk '{printf "%2.f", $3/$2 * 100.0}' | cut -d "%" -f1)
    if (($perc<=75)); then
        mem="$normal MEM $hl${perc}%"
    elif (($perc<=85)); then
        mem="$warn MEM $warn_hl${perc}%"
    elif (($perc<=99)); then
        mem="$danger MEM $danger_hl${perc}%"
    fi
    echo "M$mem"
    sleep 1;
done > $bar_fifo &

# cpu
while :
do
    echo -e 'C'$(awk -v a="$(awk '/cpu /{print $2+$4,$2+$4+$5}' /proc/stat; sleep 0.5)" '/cpu /{split(a,b," "); printf "%2.f", 100*($2+$4-b[1])/($2+$4+$5-b[2]) }'  /proc/stat)
    sleep 1;
done > $bar_fifo &

# temp
while :
do
    echo 'T'$(cat /sys/class/thermal/thermal_zone0/temp | awk '{print $1/1000}')
    sleep 3;
done > $bar_fifo &

# email
while :
do
    echo 'E'$(python ~/code/scripts/.mail)
    sleep 10;
done > $bar_fifo &

# window info
#while :
#do
#    echo 'I'$(herbstclient attr clients.focus.title)
#    sleep .5;
#done > $bar_fifo &

# tags
herbstclient -i | grep --line-buffered "tag_change" > $bar_fifo &

## bar
while read -r line ; do
    case $line in D*)
            date="$normal ${line#?}$clr"
            ;;
        H*)
            clock=" $hl ${line#?}$clr"
            ;;
        I*)
            window="$clr${line#?}"
            ;;
        E*)
            email="$light MAIL $light_hl${line#?}$clr"
            ;;
        M*)
            mem="${line#?}$clr"
            ;;
        C*)
            cpu="$normal CPU $hl${line#?}%$clr"
            ;;
        T*)
            tmp="$normal TEMP $hl${line#?}°$clr"
            ;;
        tag*)
            monitor=0
            wm_infos=""
            TAGS=( $(herbstclient tag_status $monitor) )
            # cut last element (float tag)
            unset 'TAGS[${#TAGS[@]}-1]'
            for i in "${TAGS[@]}" ; do
                case ${i:0:1} in
                    '#')
                        # focused occupied desktop
                        wm_infos="${wm_infos}$hl_inv ${i:1}$clr"
                        ;;
                    '+')
                        # focused free desktop
                        wm_infos="${wm_infos}%{+u}$u_highlight ${i:1}$clr%{-u}"
                        ;;
                    '!')
                        # focused urgent desktop
                        wm_infos="${wm_infos} ${i:1}$clr"
                        ;;
                    '%')
                        # different monitor focused
                        wm_infos="${wm_infos}$occupied ${i:1}$clr"
                        ;;
                    '-')
                        # different monitor unfocused
                        wm_infos="${wm_infos}%{+u}$u_occupied ${i:1}$clr%{-u}"
                        ;;
                    ':')
                        # occupied desktop
                        wm_infos="${wm_infos}$occupied2 ${i:1}$clr"
                        ;;
                    *)
                        # free desktop
                        wm_infos="${wm_infos} ${i:1}$clr"
                        ;;
                esac
                shift
            done
            wm_infos="$dark-<$clr${wm_infos}$dark >-$clr"
            ;;
    esac
    printf "%s\n" "%{l}$date$clock%{c}$wm_infos%{r}$email $tmp $cpu $mem"

done < "$bar_fifo" | lemonbar $geometry$parameters | sh &

wait
