#!/usr/bin/env sh

pkill bar

# Terminate already running bar instances
#killall -q bar bar_2

# Wait until the processes have been shut down
while pgrep -x bar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
. ~/.config/lemonbar/bar_l &
. ~/.config/lemonbar/bar_r &

echo "Bars launched..."
