#!/bin/sh
#
# FlyingBBQ - pow
#
# system info with local weather
#

distro="$(cat /etc/*-release | grep PRETTY_NAME | cut -d '=' -f2 | tr -d '"')"
shell="$(echo $SHELL | cut -c 6-)"
wm="$(wmctrl -m | grep Name: | cut -d ' ' -f2)"
packages="$(pacman -Qq | wc -l)"
font="tamsyn"

while getopts ':hw' arg
do
    case $arg in
        h) HZ=true
            ;;
        w) weather=$(curl -s wttr.in | awk 'NR>=2 && NR<=7')
            ;;
        *) weather=""
            ;;
    esac
done

if [ "$HZ" = true ];
then
    # Horizontal
    printf "\033[0m\r\n"
    printf "\033[1;31m  █  \033[0m\r\n"
    printf "\033[1;32m  █  \033[1;33m%-8s  \033[0m%-16s %-20s\r\n" "distro"   "$distro"   "$(printf "$weather" | sed -n -e 2p)"
    printf "\033[1;33m  █  \033[1;33m%-8s  \033[0m%-16s %-20s\r\n" "packages" "$packages" "$(printf "$weather" | sed -n -e 3p)"
    printf "\033[1;34m  █  \033[1;33m%-8s  \033[0m%-16s %-20s\r\n" "shell"    "$shell"    "$(printf "$weather" | sed -n -e 4p)"
    printf "\033[1;35m  █  \033[1;33m%-8s  \033[0m%-16s %-20s\r\n" "wm"       "$wm"       "$(printf "$weather" | sed -n -e 5p)"
    printf "\033[1;36m  █  \033[1;33m%-8s  \033[0m%-16s %-20s\r\n" "font"     "$font"     "$(printf "$weather" | sed -n -e 6p)"
    printf "\033[1;37m  █  \033[0m\r\n"

else
    # Vertical
    printf "\033[0m\r\n"
    printf "\033[1;33m%14s \033[0m%-16s\r\n" "distro"   "$distro"
    printf "\033[1;33m%14s \033[0m%-16s\r\n" "packages" "$packages"
    printf "\033[1;33m%14s \033[0m%-16s\r\n" "shell"    "$shell"
    printf "\033[1;33m%14s \033[0m%-16s\r\n" "wm"       "$wm"
    printf "\033[1;33m%14s \033[0m%-16s\r\n" "font"     "$font"
    [ "$weather" ] && printf "$weather\r\n"
    printf "\033[0m\r\n"
    printf "\033[1;31m     ▀ \033[1;32m ▀ \033[1;33m ▀ \033[1;34m ▀ \033[1;35m ▀ \033[1;36m ▀ \033[1;37m ▀ \n"
fi

printf "\033[0m\r\n"
