#! /bin/sh
#
# bspwm@FlyingBBQ
#

#--- bar
. ~/.config/polybar/polybar.sh

#--- wallpaper
feh --bg-fill ~/images/wallpapers/FUAY5i8.png

#--- lock
. ~/code/scripts/lock.sh

#--- bspwm
bspc monitor -d I II III IV V VI 

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color  \#FE8019
bspc config normal_border_color   \#282828
bspc config presel_feedback_color \#504945

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#--- redshift
redshift -c ~/.config/redshift.conf &
