#! /bin/sh
#
# FlyingBBQ @ Bar
#

## Colors

. ~/.dotfiles/panel/bar_colors

## Config
screen_width=1920
bar_fifo=/tmp/bar-fifo-2
bar_font="-f -misc-tamsyn-medium-r-normal--16-116-100-100-c-80-iso8859-1"
bar_width=1500
bar_height=30
bar_y=10
bar_x=$(( 1920+($screen_width - $bar_width)/2 ))

geometry="-g ${bar_width}x${bar_height}+${bar_x}+${bar_y}"
parameters=" $bar_font -B $a$bg -F $a$fg -u 3"

## Initialize
if [ $(pgrep bar_2) -gt 1]
then 
    pkill bar_2
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$bar_fifo" ] && rm "$bar_fifo"
mkfifo "$bar_fifo"

## Modules

# tags
while :
do
    monitor=1
    wm_infos=""
    TAGS=( $(herbstclient tag_status $monitor) )
    for i in "${TAGS[@]}" ; do
        case ${i:0:1} in
            '#')
                # focused occupied desktop
                wm_infos="${wm_infos}$hlinv ${i:1}$clr"
                ;;
            '+')
                # focused free desktop
                wm_infos="${wm_infos}%{+u}$u_highlight ${i:1}$clr%{-u}"
                ;;
            '!')
                # focused urgent desktop
                wm_infos="${wm_infos} ${i:1}$clr"
                ;;
            '%')
                # different monitor focused
                wm_infos="${wm_infos}$occupied ${i:1}$clr"
                ;;
            '-')
                # different monitor unfocused
                wm_infos="${wm_infos}%{+u}$u_occupied ${i:1}$clr%{-u}"
                ;;
            ':')
                # occupied desktop
                wm_infos="${wm_infos}$occupied2 ${i:1}$clr"
                ;;
            *)
                # free desktop
                wm_infos="${wm_infos} ${i:1}$clr"
                ;;
        esac
        shift
    done
    echo "W$wm_infos"
    sleep .1
done > $bar_fifo &

## bar
~/.dotfiles/panel/bar_fifo_2 < "$bar_fifo" | lemonbar $geometry$parameters | sh &

wait
