#! /bin/sh

## colors
a="#"
bg2="3c3836"
bg3="504945"
bg4="777777"
bg=$(xrdb -query|awk '/\*background/ {print $2}'|cut -d '#' -f2)
fg=$(xrdb -query|awk '/\*foreground/ {print $2}'|cut -d '#' -f2)
blk=$(xrdb -query|awk '/\*color0:/ {print $2}'|cut -d '#' -f2)
bblk=$(xrdb -query|awk '/\*color8:/ {print $2}'|cut -d '#' -f2)
red=$(xrdb -query|awk '/\*color1:/ {print $2}'|cut -d '#' -f2)
grn=$(xrdb -query|awk '/\*color2:/ {print $2}'|cut -d '#' -f2)
ylw=$(xrdb -query|awk '/\*color3:/ {print $2}'|cut -d '#' -f2)
blu=$(xrdb -query|awk '/\*color4:/ {print $2}'|cut -d '#' -f2)
mag=$(xrdb -query|awk '/\*color5:/ {print $2}'|cut -d '#' -f2)
cyn=$(xrdb -query|awk '/\*color6:/ {print $2}'|cut -d '#' -f2)
wht=$(xrdb -query|awk '/\*color7:/ {print $2}'|cut -d '#' -f2)

## highlighting
dark="%{B$a$bg}%{F$a$bg4}$PR"
normal="%{B$a$bg2}%{F$a$fg}$PR"
light="%{B$a$bg3}%{F$a$fg}$PR"
light_high="%{B$a$bg3}%{F$a$ylw}$PR"
highlight="%{B$a$bg2}%{F$a$ylw}$PR"
hlinv="%{B$a$ylw}%{F$a$bg}$PR"
occupied="%{B$a$bg3}%{F$a$ylw}$PR"
occupied2="%{B$a$bg}%{F$a$ylw}$PR"
u_occupied="%{B$a$bg}%{F$a$ylw}%{U$a$bg4}$PR"
u_highlight="%{B$a$bg}%{F$a$ylw}%{U$a$ylw}$PR"
power="%{B$a$blu}%{F$a$fg}$PR"
power_hl="%{B$a$blu}%{F$a$ylw}$PR"
full="%{B$a$cyn}%{F$a$fg}$PR"
full_hl="%{B$a$cyn}%{F$a$ylw}$PR"

## variables
PL=" "
PR=" "
clr="$PL%{F-}%{B-}"
